### ISSUE TITLE
when you are decoding, you use convolution, but why the weights are not flipped over? 

### ISSUE THREAD

**Issue by markofan** [ehosseiniasl/3d-convolutional-network#7]
when you are encoding, use the code:
self.hidden_layer=ConvolutionLayer3D(rng,
                                             input=self.inputs,
                                             signal_shape=signal_shape,
                                             filter_shape=filter_shape,
                                             act=activation,
                                             border_mode='full',
                                             if_hidden_pool=False)

when you are decoding, use the code:
self.recon_layer=ConvolutionLayer3D(rng,
                                 input=self.hidden_layer.output,
                                 signal_shape=self.hidden_image_shape,
                                 filter_shape=self.hidden_filter_shape,
                                 act=activation,
                                 border_mode='valid')
Your paper write To reduce the number of the free parameters, the decoding, P k , and encoding, W k , weights were tied by flipping over all their dimensions as proposed in.
So I want to ask, why there is no flipping over in the code? Or did I miss something?

**Comment by ehosseiniasl** [comment]
Thanks for the comment.
this is the vanilla version of cae w/o tied weights. This will be updated!
