### ISSUE TITLE
Hi I want to know what is the cost when you doing your pre_training CAE?

### ISSUE THREAD

**Issue by markofan** [ehosseiniasl/3d-convolutional-network#9]
When I doing my pre_training CAE2, my cost is about 100 every data, I think it is abnormal, what is your cost when you doing your pre_train?

**Comment by markofan** [comment]
batch:23        cost:140.49     time:0.27
batch:24        cost:169.58     time:0.28
batch:25        cost:142.37     time:0.27
batch:26        cost:190.42     time:0.27
batch:27        cost:160.19     time:0.27
batch:28        cost:225.43     time:0.28
batch:29        cost:171.72     time:0.27

Here is my CAE2's cost. It looks so strange! my batch_size=4

**Comment by Houchaoqun** [comment]
@markofan 
hello, markofan
I'm studing the author's code recently. Could you please tell me about the following questions:
1. How to download the pretained dataset (source domain)?
2. I have downloaded the AD dataset according to the author's ADNI_subject_id directory. But how to transfer the original AD dataset to .mat file.

I'm looking forward to your reply, thanks.
